* Cond-Let — Additional and improved binding conditionals

*This is an ALPHA release!*
*Breaking changes are possible!*

Emacs provides the binding conditionals ~if-let~, ~if-let*~,
~when-let~, ~when-let*~, ~and-let*~ and ~while-let~.  Starting
with Emacs 31 it also provides ~cond-let*~.

This package implements the missing ~and-let~, ~while-let*~ and
~cond-let~.  It also implements the original ~and$~ and ~and>~.

This package additionally provides more consistent and improved
implementations of the binding conditionals already provided by
Emacs.  Merely loading this library does not shadow the built-in
implementations; this can optionally be done in the context of
an individual library, as described below.

The names of all macros implemented by this package begin with
~cond-let--~, the package's prefix for private symbol.

(In the initial release of this package ~cond-let~ and ~cond-let*~
were provided exactly under these names (without the ~cond-let--~
prefix), because these forms did not exist in Emacs at that time.
Later an incompatible implementation of ~cond-let*~ was added to
Emacs, forcing us to rename our implementation.  To avoid having
a single un-prefixed form, we also add the prefix to ~cond-let~.)

Users of this package are not expected to use these unwieldy
names.  Instead one should use Emacs' shorthand feature to use
all or some of these macros by their conceptual names.

Please see the library header for usage information and the
docstrings for information about the individual macros.
See also https://github.com/tarsius/cond-let/wiki.
